# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: serverchat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10serverchat.proto\x12\x04grpc\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n\x0b\x43hatMessage\x12\x17\n\x0fsender_username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"j\n\x15\x43hatMessageFromServer\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x07message\x18\x02 \x01(\x0b\x32\x11.grpc.ChatMessage2T\n\x0b\x43hatService\x12\x45\n\x0fSendChatMessage\x12\x11.grpc.ChatMessage\x1a\x1b.grpc.ChatMessageFromServer(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serverchat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CHATMESSAGE']._serialized_start=59
  _globals['_CHATMESSAGE']._serialized_end=114
  _globals['_CHATMESSAGEFROMSERVER']._serialized_start=116
  _globals['_CHATMESSAGEFROMSERVER']._serialized_end=222
  _globals['_CHATSERVICE']._serialized_start=224
  _globals['_CHATSERVICE']._serialized_end=308
# @@protoc_insertion_point(module_scope)
